### PR TITLE
add new feature

### PR DESCRIPTION
**Pull request by shugen002**
i add some useful feature
show position , health ,weather and food

### CODE REVIEW

**Comment by rom1504** [comment]
What is `public/Thumbs.db` ?
Otherwise, good idea !

**Comment by shugen002** [comment]
it is generate by window . 
i am very sorry for it.
i haven' t notice that the file is in my commit .please ignore it.

**Comment by rom1504** [comment]
Well, can you add an other commit to remove it ?

**Comment by shugen002** [comment]
ok i commit it

**Comment by shugen002** [comment]
by the way , can you tell me some tips to setup the .gitignore to avoid from making the same mistake again .
thank you so much

**Comment by shugen002** [comment]
i am waiting for you merge

**Comment by rom1504** [comment]
Ah yeah sorry I hadn't have time to test this.

**Comment by rom1504** [comment]
You can use .git/info/exclude if you want git to ignore files but not put them in .gitignore

**Pull request merged**
