### PR TITLE
add multi version support and support show kicked reason

### PR DESCRIPTION
**Pull request by shugen002**
Though you don't have time to update it , I do !

PS: 
I hope you can update the version and repository in package.json and publish it.
Thank you!

1.7 support may not work before you make mineflayer support it.
but i add it . Because i don't have more time until june , 2017 , and i hope  when mineflayer support 1.7 ,this project is ready .

The reason why i changed Gruntfile is the origin doesn't work . 

> Fatal error: Path must be a string. Received [ 'bin/start' ]

so i changed it.

If I make any English grammar mistake in this comment ,  please tell me .

### CODE REVIEW

**Comment by shugen002** [comment]
By the way , maybe it can end #4  and #5

**Comment by shugen002** [comment]
Yes , i decide not to add 1.7 in to selections . no because.

and i check why i can't use 1.7 .It is the PrismarineJS/prismarine-chunk didn't support 1.7 .

**Comment by ghost** [comment]
Looks good! :+1:

**Comment by rom1504** [comment]
Oh I forgot to look at this, Is this still up to date ? I'll have a look

**Comment by shugen002** [comment]
It's so long time after my last check . maybe this project need a big update?

~~I don't think it still work because many dependence have been change a lot.
That why i chose to close this PR .~~

Oh I check it . It still works and i think it need some update

**Pull request merged**
